---

name: AWS AMI using Packer Config

on: push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          # if you have/need it
          aws-region: us-east-1

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        working-directory: .github
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        working-directory: .github
        with:
          command: validate
          arguments: -syntax-only
          target: build.pkr.hcl

      # build artifact.
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        working-directory: .github
        with:
          command: build
          arguments: "-color=false -on-error=abort -var checkout=${{ github.sha }}"
          target: build.pkr.hcl
        env:
          PACKER_LOG: 1
